spring.application.name=Manage-Mosaic

server.port=8028
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/manage_mosaic
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

spring.security.oauth2.client.registration.google.client-id=662111002101-797vmf6dcffvn0vbkr96gj6u01rfsmgd.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/login/oauth2/code/google
spring.security.oauth2.client.registration.google.scope=profile,email
spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo
